### ISSUE TITLE
I installed pligg 2.02 via Softaculous. when submitting ANY url, it gives me the URL is invalid or blocked message.

### ISSUE THREAD

**Issue by legalfirm** [Kliqqi-CMS/Kliqqi-CMS#253]
I installed pligg 2.02 via Softaculous. when submitting ANY url, it gives me the URL is invalid or blocked message.
http://law.bestsquarefeet.com/

**Comment by chuckroastpligg** [comment]
We are Kliqqi as of 2014. You installed a very outdated insecure version of Pligg CMS which is no longer supported anywhere.  I can only suggest you install Kliqqi which is available from Kliqqi.com
